name: HazeMT-Plots
version: '${project.version}'
main: me.crqptx.MTPlots.Main
depend: [ WorldGuard ]
api-version: 1.12
authors: [ Crqptx ]
description: HazeMT Plots Plugin.
commands:
  pi:
    description: "Plot info"
  hplots:
    description: "Help Menu"